### ISSUE TITLE
As a seller, I want the cost of the product before and after the shipping fees to be showed, because I want to show the customer exactly the details of the purchase.

### ISSUE THREAD

**Issue by beshoikhair** [karyennevu/GENERALs-soen341project2022#38]
User Story for Core Feature #23 on Adding Items to shopping carts.

**Comment by beshoikhair** [comment]
@karyennevu Please review this user story and suggest what are its Potential Risks
@DragonGawain Please review the user story and the risks and close the issue.
Thank you

**Comment by karyennevu** [comment]
If the system only displays one of the totals (the before shipping price OR the after shipping price) then there is a risk that it would create confusion to the customer, because they won't know if the shipping is included in the total or not, and so this could lead to the customer being unhappy when they find out that the total comes out higher than they expected. We suggest displaying the costs of the order in full details before letting customer place their orders to avoid confusion and unhappy customers.

**Comment by DragonGawain** [comment]
Given that I am a seller, 
After a customer adds items to their cart
And viewing the items in their cart
I should be able to show them the price of the items alone
And the price of the items with the shipping cost separately

Success case:
Both item prices are listed

Failure case:
There is only one final price listed

**Comment by maxxfreund** [comment]
Acceptance tests and risks verified. 
Closing user story.
