### ISSUE TITLE
As a Seller, I want the customer to be able to add coupons on some of my products, because I want to encourage them to buy specific products.

### ISSUE THREAD

**Issue by beshoikhair** [karyennevu/GENERALs-soen341project2022#42]
User Story for Core Feature #23 on Adding Items to shopping carts.

**Comment by beshoikhair** [comment]
@karyennevu Please review this user story and suggest what are its Potential Risks
@DragonGawain Please review the user story and the risks and close the issue.
Thank you

**Comment by karyennevu** [comment]
If the coupon is given to a customer, but then the system does not apply the discount, then there is a risk that the customer loses interest in the product since the coupon was an incentive and so there could be a wasted potential sale increase. We suggest that the coupons and discount codes be implemented and tested properly before sending them out to customers.

**Comment by DragonGawain** [comment]
Acceptance tests have been verified.
Risks have been verified. 
Marking user story as closed.
