### ISSUE TITLE
As an admin, I want to access the Wishlist of each user, because I want to show related products to each customer's interests.

### ISSUE THREAD

**Issue by beshoikhair** [karyennevu/GENERALs-soen341project2022#45]
User Story for Core Feature #23 on Adding Items to shopping carts.
Additional feature #48 - wishlist

**Comment by beshoikhair** [comment]
@karyennevu Please review this user story and suggest what are its Potential Risks
@DragonGawain Please review the user story and the risks and close the issue.
Thank you

**Comment by karyennevu** [comment]
If the system does not give access to the Wishlist of the website's users, then there is a risk that the products advertised to each customers may not be tailored to their interests due to the lack of data for the algorithm and so there would be a waste of potential sales. We suggest giving the admin and staffs access to view only the Wishlist of customers to increase potential sales and improve the product advertisements on the website.

**Comment by DragonGawain** [comment]
When accessing a user's account
I should be able to view the items in their wishlist
and change which items are being suggested to the user based on the items in their wishlist

Success case:
Suggested items for the user change

Failure casses:

Suggested items do not change (assuming a change is necessary)

Wishlist cannot be access

User account cannot be accessed

**Comment by DragonGawain** [comment]
Risks and acceptance tests verified.
